export const LetterListRow = [];
LetterListRow[1] = ["Q","W","E","R","T","Y","U","I","O","P"];
LetterListRow[2] = ["A","S","D","F","G","H","J","K","L"];
LetterListRow[3] = ["Z","X","C","V","B","N","M"];
export const Words = {
"Games":["Counter Strike","Fortnite","Minecraft","League of Legends","Valorant","Far Cry","Assassins Creed","FIFA","Grand Theft Auto","The Witcher","Gran Turismo","Assetto Corsa","Rocket League","Overwatch","Call of Duty","World of Warcraft","Hearthstone","God of War","The Last of Us","Red Dead Redemption","The Sims","Resident Evil","Half Life","Dark Souls","Dying Light","Mortal Kombat","Rainbow Six Siege"],
"Companies":["Apple","Microsoft","Amazon","Samsung","Netflix","Walmart","Berkshire Hathaway","Cardinal Health","Wells Fargo","Procter & Gamble","Walt Disney","Boeing","Pfizer","Nike","Adidas","Starbucks","PayPal","McDonalds","Mastercard","Salesforce","Hasbro","Chevron","Bosch","Unilever","Continental","Oracle","Cisco Systems","Tencent","Taiwan Semiconductor","Qualcomm","Philips","Sony","Nintendo"],
"Foods & Drinks":["French fries","Hamburger","Sausage","Pizza","Apple","Orange","Banana","Cherry","Kiwi","Coconut","Pomegranate","Potato","Tomato","Asparagus","Eggplant","Onion","Pumpkin","Brocoli","Spinach","Mushroom","Hotdog","Sandwich","Omelet","Pancake","Wine","Coffee","Milkshake","Smoothie","Lemonade","Water","Coca-Cola","Sprite","Schweppes"],
"Animals":["Chicken","Elephant","Monkey","Penguin","Whale","Scorpion","Flamingo","Jellyfish","Dolphin","Reindeer","Rhinoceros","Grizzly Bear","Beaver","Salmon","Parrot","Pigeon","Alligator","Coyote","Crocodile","Grasshopper","Gorilla","Guinea pig","Komodo Dragon","Lizard","Raccoon","Rabbit","Rattlesnake","Seahorse","Bald eagle","Wolf","Zebra"],
"Countries & Cities":["United States of America","Afghanistan","Argentina","Bangladesh","Belgium","Colombia","Croatia","Cyprus","Denmark","Estonia","Finland","France","Germany","Guatemala","Hungary","Iceland","Indonesia","India","China","Liechtenstein","Luxembourg","Madagascar","Lithuania","Netherlands","Pakistan","Poland","Romania","Saudi Arabia","Sierra Leone","South Africa","South Korea","Sweden","Switzerland","United Arab Emirates","United Kingdom","Uzbekistan","Venezuela"],
"Automakers":["Toyota","Lexus","Volkswagen","Hyundai","General Motors","Ford","Nissan","Honda","Renault","Suzuki","Mercedes-Benz","BMW","Mazda","Mitsubishi","Chevrolet","Buick","Cadillac","Fiat","Dodge","Alfa Romeo","Audi","Porsche","Lamborghini","Citroen","Peugeot","Opel","Skoda","Bentley","Ferrari","Jaguar","Maserati","Lotus","Subaru","Aston Martin","Bugatti","Koenigsegg","McLaren","Mini","Volvo","Tesla"]
};